# Generated by Django 5.2.7 on 2025-11-04 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hasher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hash_name', models.CharField(max_length=69)),
                ('nerd_first', models.CharField(max_length=30)),
                ('nerd_last', models.CharField(max_length=30)),
                ('hash_nickname', models.CharField(max_length=30)),
                ('just_name', models.CharField(max_length=30)),
                ('home_kennel', models.CharField(max_length=30)),
                ('current_kennel', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('state_province', models.TextField()),
                ('zip_postal_code', models.TextField()),
                ('country', models.TextField()),
                ('hash_cash_balance', models.FloatField()),
                ('hash_cash_exampe', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=255)),
                ('role_description', models.CharField(max_length=255)),
                ('hash_cash_exempt', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StatsYear',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('year_name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('hash_cash', models.FloatField()),
            ],
            options={
                'db_table': 'stats_year',
            },
        ),
        migrations.CreateModel(
            name='StatsYearRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.hasher')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.role')),
                ('stats_year_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.statsyear')),
            ],
            options={
                'db_table': 'stats_year_roles',
            },
        ),
    ]
