# Generated by Django 5.2.7 on 2025-11-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hasher',
            old_name='hash_cash_exampe',
            new_name='hash_cash_exempt',
        ),
        migrations.AlterField(
            model_name='hasher',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hasher',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hasher',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hasher',
            name='state_province',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='hasher',
            name='zip_postal_code',
            field=models.CharField(max_length=10),
        ),
    ]
