# Generated by Django 5.2.7 on 2025-11-06 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_rename_hash_cash_exampe_hasher_hash_cash_exempt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statsyearroles',
            options={'verbose_name_plural': 'Stats year roles'},
        ),
        migrations.AlterModelTable(
            name='statsyearroles',
            table='stats_year_role',
        ),
    ]
