# Generated by Django 5.2.7 on 2025-11-07 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_alter_statsyearroles_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('award_name', models.CharField(max_length=100)),
                ('award_description', models.CharField(max_length=255)),
                ('num_trails', models.IntegerField()),
                ('stats_year_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.statsyear')),
            ],
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('trail_date', models.DateField()),
                ('trail_description', models.CharField(max_length=255)),
                ('trail_start', models.TimeField()),
                ('trail_start_location', models.CharField(max_length=255)),
                ('checks', models.TextField()),
                ('trail_end', models.TimeField()),
                ('trail_end_location', models.CharField(max_length=255)),
                ('map', models.ImageField(upload_to='')),
                ('trash', models.FileField(upload_to='trails/trash')),
                ('video', models.FileField(upload_to='trails/video')),
                ('distance_turkey', models.FloatField()),
                ('distance_eagle', models.FloatField()),
                ('temperature', models.FloatField()),
                ('cases', models.FloatField()),
                ('published_in_stats', models.BooleanField()),
                ('namings', models.ManyToManyField(related_name='trail_namings', to='stats.hasher')),
                ('stats_year_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.statsyear')),
                ('visitors', models.ManyToManyField(related_name='trail_visitors', to='stats.hasher')),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_at_trail', models.CharField(max_length=255)),
                ('hare', models.BooleanField()),
                ('hasher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.hasher')),
                ('trail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.trail')),
            ],
        ),
    ]
