# Generated by Django 5.2.7 on 2025-11-07 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_award_trail_pack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trail',
            old_name='id',
            new_name='trail_id',
        ),
    ]
