# Generated by Django 5.2.7 on 2025-11-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_rename_id_trail_trail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='map',
            field=models.FileField(upload_to='trails/map'),
        ),
    ]
