# Generated by Django 5.2.7 on 2025-11-12 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_alter_trail_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasherStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Hasher statuses',
            },
        ),
        migrations.AddField(
            model_name='hasher',
            name='first_trail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.trail'),
        ),
        migrations.AddField(
            model_name='hasher',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.hasherstatus'),
        ),
    ]
