# Generated by Django 5.2.7 on 2025-11-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_hasherstatus_hasher_first_trail_hasher_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasher',
            name='mugshot',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hasher',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='hasher',
            name='birth_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='hasher',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hasher',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hasher',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='hasher',
            name='state_province',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='hasher',
            name='zip_postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.RemoveField(
            model_name='trail',
            name='namings',
        ),
        migrations.AddField(
            model_name='trail',
            name='namings',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
