# Generated by Django 5.2.7 on 2025-11-15 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_hasher_mugshot_alter_hasher_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasher',
            name='mugshot',
            field=models.ImageField(blank=True, upload_to='mugshots'),
        ),
        migrations.CreateModel(
            name='TrailPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(upload_to='trails/photos')),
                ('trail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.trail')),
            ],
        ),
    ]
