# Generated by Django 5.2.7 on 2025-11-24 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_alter_hasher_mugshot_trailphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailphoto',
            name='attribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.hasher'),
        ),
        migrations.AlterField(
            model_name='statsyear',
            name='year_name',
            field=models.CharField(max_length=69),
        ),
    ]
