# Generated by Django 5.2.7 on 2026-02-06 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_trailphoto_attribution_alter_statsyear_year_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hasher',
            name='first_trail',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='cases',
        ),
        migrations.AddField(
            model_name='hasher',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='hasher',
            name='pi_visible',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='pack',
            name='new_boot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pack',
            name='transplant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pack',
            name='wanker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trail',
            name='dfl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trail_dfl', to='stats.hasher'),
        ),
        migrations.AddField(
            model_name='trail',
            name='distance_comment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trail',
            name='fbi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trail_fbi', to='stats.hasher'),
        ),
        migrations.AddField(
            model_name='trail',
            name='frb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trail_frb', to='stats.hasher'),
        ),
        migrations.AddField(
            model_name='trail',
            name='golden_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hasher',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hasher',
            name='hash_cash_exempt',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pack',
            name='hare',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trail',
            name='checks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='distance_eagle',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='trail',
            name='distance_turkey',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='trail',
            name='map',
            field=models.FileField(blank=True, upload_to='trails/map'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='namings',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='trail_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='trail',
            name='trail_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='trail_end_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='trail',
            name='trail_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='trail_start_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='trail',
            name='trash',
            field=models.FileField(blank=True, upload_to='trails/trash'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='video',
            field=models.FileField(blank=True, upload_to='trails/video'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='visitors',
            field=models.ManyToManyField(blank=True, related_name='trail_visitors', to='stats.hasher'),
        ),
    ]
