# Generated by Django 5.2.7 on 2026-02-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_remove_hasher_first_trail_remove_trail_cases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasher',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddConstraint(
            model_name='pack',
            constraint=models.UniqueConstraint(fields=('trail_id', 'hasher_id'), name='unique_trail_hasher_combo'),
        ),
    ]
