# Generated by Django 5.2.7 on 2026-02-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_hasher_phone_pack_unique_trail_hasher_combo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='dnf',
            field=models.BooleanField(default=False),
        ),
    ]
