# Generated by Django 5.2.7 on 2026-02-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0013_pack_dnf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='dfl',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='fbi',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='frb',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='visitors',
        ),
        migrations.AddField(
            model_name='pack',
            name='dfl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pack',
            name='fbi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pack',
            name='frb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pack',
            name='visitor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trail',
            name='trail_zip_postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddConstraint(
            model_name='pack',
            constraint=models.UniqueConstraint(condition=models.Q(('frb', True)), fields=('trail_id',), name='unique_trail_frb'),
        ),
        migrations.AddConstraint(
            model_name='pack',
            constraint=models.UniqueConstraint(condition=models.Q(('fbi', True)), fields=('trail_id',), name='unique_trail_fbi'),
        ),
        migrations.AddConstraint(
            model_name='pack',
            constraint=models.UniqueConstraint(condition=models.Q(('dfl', True)), fields=('trail_id',), name='unique_trail_dfl'),
        ),
        migrations.AddConstraint(
            model_name='pack',
            constraint=models.UniqueConstraint(condition=models.Q(('new_boot', True)), fields=('hasher_id',), name='unique_hasher_new_boot'),
        ),
    ]
